### PR TITLE
magic runtime

### PR DESCRIPTION
**Pull request by missinglink**
WIP

these changes make it so that `env` vars are no longer required at runtime 🎩 🐰 
you can unset `$RUNTIME` as well as `$LD_LIBRARY_PATH`, none are required and will in fact be ignored if you have them set.

@Joxit could you please re-compile your runtime and test this on your Debian env and try it out?
You'll also need to blow away `node_modules` and reinstall.

I'd like to clean up the commits a little before merging if it works on nix like it does on mac.

One thing I'm still not 💯 on is `PROJ_LIB="${RUNTIME}/data"` as it doesn't seem able to 'bake it in' like with `rpath`, moving the files to `${RUNTIME}/share/proj` might resolve this.

### CODE REVIEW

**Comment by missinglink** [comment]
unfortunately this appears to not work in `alpine`, I'm going to put it down for a while and have another look later.

**Comment by missinglink** [comment]
Okay! I think this is good to go, I changed some more stuff to get the `ICU` dependency linking correctly.
It will require `clang` to be installed but that's not a big deal.

**Comment by Joxit** [comment]
Okay :rocket: 

So you removed alpine image ?

**Comment by missinglink** [comment]
Yeah, I would like to have all the Pelias docker images based on `pelias/baseimage` because it contains some functionality for setting the user permissions, and keeps thing more consistent and easier to modify.

**Comment by missinglink** [comment]
I managed to get the docker image size down from `1.3GB` to `~700MB` by using the multi-step build.

One of the major advantages is not in excluding the tests files and fixtures (which I'm actually leaving in there) but in using the `npm install --production` step, my testing showed that something in our dev dependencies is bringing in `typescript` which is ~100MB and another one I forget which...

I just republished the `pelias/spatial` image based off `pelias/baseimage` instead of `alpine`, it's about twice the size but its fine, if we trim `pelias/baseimage` at some point this will get smaller too!

**Pull request merged**
