### PR TITLE
buster Dockerfile

### PR DESCRIPTION
**Pull request by missinglink**
this is a WIP to demonstrate how to run the spatial service on the `debian/buster` operating system.

```
docker build -t 'pelias/spatial:buster' -f buster.Dockerfile .
```

I commented out a bunch of stuff that turned out to be irrelevant, but I still don't understand why removing any of the paths in `InitExtension.js` causes a `SIGSEGV` 🤷‍♂ 

If you see this in the output then it successfully loaded `spatialite`:

```
  features
    ✓ HasIconv
    ✓ HasIconv
    ✓ HasMathSQL
    ✓ HasMathSQL
    ✓ HasProj
    ✓ HasProj
    ✓ HasGeos
    ✓ HasGeos
    ✓ HasGeosAdvanced
    ✓ HasGeosAdvanced
    ✓ HasGeosTrunk
    ✓ HasGeosTrunk
    ✓ HasGeosReentrant
    ✓ HasGeosReentrant
    ✓ NOT HasLwGeom
    ✓ HasRtTopo
    ✓ HasRtTopo
    ✓ HasLibXML2
    ✓ HasLibXML2
    ✓ HasEpsg
    ✓ HasEpsg
    ✓ HasFreeXL
    ✓ HasFreeXL
    ✓ HasGeoPackage
    ✓ HasGeoPackage
```

### CODE REVIEW

**Comment by missinglink** [comment]
It's particularly odd that removing the line which checks for `/code/build/tmp/libspatialite-5.0.0-beta1/src/.libs/libspatialite.so` makes it fail but the file doesn't even exist!

Even changing that path slightly results in a failure, which makes no sense at all considering `ls: cannot access '/code/build/tmp': No such file or directory`

**Comment by Joxit** [comment]
Awesome ! Well job ! 

I did two changes
```diff
const searchPaths = [{
-  extpath: '/usr/lib/x86_64-linux-gnu',
+  extpath: '/usr/local/lib',
  extinit: 'libspatialite.so'
}]
```

Because I built spatialite by hand on my latptop, so v5.0.0 is on /usr/local/lib and v4.3.0 is on /usr/lib/x86_64-linux-gnu.

I need to run commands with `LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib` in order to use v5.0.0 instead of v4.

Tests gives me 2 errors (because of versions) and 0 SEG Fault !
```
 FAIL  test/environment.js 2 failed of 15 483.839ms
 ✖ sqlite_version: 3.27.2
 ✖ libxml2_version: 2.9.4
```

But... (I'm sorry....) when I try an import .... Seg fault :cry: 
This may be caused by an incompatibility between SQLite3 from amalgamation and the SQLite I used for spatialite build.... I will do more investigation on this, but it's better now thanks ! :D 

Here is the error 
```
InitExtension.load()
lib { extpath: '/usr/local/lib', extinit: 'libspatialite.so' }
p /usr/local/lib/libspatialite.so
loadExtension('/usr/local/lib/libspatialite.so')
SqliteError: /usr/local/lib/libspatialite.so: undefined symbol: sqlite3_spatialite_init
    at InitExtension.load (/home/joxit/pelias/node_modules/spatial/module/spatialite/InitExtension.js:77:12)
    at InitExtension.create (/home/joxit/pelias/node_modules/spatial/module/spatialite/InitExtension.js:89:15)
    at SpatialiteModule.setup (/home/joxit/pelias/node_modules/spatial/module/Module.js:12:23)
    at new ImportService (/home/joxit/pelias/node_modules/spatial/service/ImportService.js:53:25)
    at Object.handler (/home/joxit/pelias/node_modules/spatial/bin/cmd/import.js:77:21)
    at Object.runCommand (/home/joxit/pelias/node_modules/spatial/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/joxit/pelias/node_modules/spatial/node_modules/yargs/yargs.js:1078:30)
    at Object.parse (/home/joxit/pelias/node_modules/spatial/node_modules/yargs/yargs.js:542:19)
    at Object.<anonymous> (/home/joxit/pelias/node_modules/spatial/bin/spatial.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

I will do some other tests later :)

**Comment by Joxit** [comment]
I may found a same issue on [mattn/go-sqlite3#516](https://github.com/mattn/go-sqlite3/issues/516). The solution was an update of a dependency [shaxbee/go-spatialite#2](https://github.com/shaxbee/go-spatialite/pull/2).

go-spatialite use `conn.LoadExtension(v.lib, v.proc)` where `v.lib = "libspatialite.so"` and `v.proc = "spatialite_init_ex"` from [go-sqlite3](
https://github.com/mattn/go-sqlite3/blob/67986a7832dcbda29de5c1341b3dec6c6d97511a/sqlite3_load_extension.go#L48-L70)
`go-sqlite3` uses the C function `sqlite3_load_extension(c.db, clib, centry, nil)`
`better-sqlite3` uses the C function `sqlite3_load_extension(db->db_handle, *filename, NULL, &error)` (entry is NULL). IDK if this is relevant.

**Comment by Joxit** [comment]
Let see the error: `SqliteError: /usr/local/lib/libspatialite.so: undefined symbol: sqlite3_spatialite_init`
better-sqlite wants the function `sqlite3_spatialite_init`, but in libspatialite, the loadable function is `sqlite3_modspatialite_init` in v5.0.0

**Comment by missinglink** [comment]
```
Both methods for loading an extension allow you to specify the name of an entry point for the extension. You can leave this argument blank - passing in a NULL pointer for the sqlite3_load_extension() C-language interface or omitting the second argument for the load_extension() SQL interface - and the extension loader logic will attempt to figure out the entry point on its own. It will first try the generic extension name "sqlite3_extension_init". If that does not work, it constructs a entry point using the template "sqlite3_X_init" where the X is replaced by the lowercase equivalent of every ASCII character in the filename after the last "/" and before the first following "." omitting the first three characters if they happen to be "lib". So, for example, if the filename is "/usr/lib/libmathfunc-4.8.so" the entry point name would be "sqlite3_mathfunc_init". Or if the filename is "./SpellFixExt.dll" then the entry point would be called "sqlite3_spellfixext_init".
```

https://www.sqlite.org/loadext.html

**Comment by Joxit** [comment]
Okay, I have more intel on my issue. I'm using the command `node bin/spatial.js import whosonfirst --db=debian.db --file=/dev/null`

When I use `mod_spatialite.so` with spatialite v4.3.0a; I have a SEG fault during `setup` here 
https://github.com/pelias/spatial/blob/18bb5c7c5e813bedcc4c100b1fb8f6b704629f20/module/spatialite/InitSpatialOptions.js#L18
That's totally normal, it's a v5.0.0 feature :+1: 

When I use `mod_spatialite.so` with spatialite v5.0.0; The SEG fault appears during `config` here
https://github.com/pelias/spatial/blob/18bb5c7c5e813bedcc4c100b1fb8f6b704629f20/module/geometry/GeoColumnGeom.js#L17-L19
That's **not** normal because already present in v4.3.0....

Ok, now I use a random spatial database from data.geocode.earth :+1:, for example [whosonfirst-data-admin-xs-latest.spatial.db.bz2](https://data.geocode.earth/wof/dist/spatial/whosonfirst-data-admin-xs-latest.spatial.db.bz2).
I run the same command and the SEG fault comes during `statements` here 
https://github.com/pelias/spatial/blob/18bb5c7c5e813bedcc4c100b1fb8f6b704629f20/module/geometry/StatementInsert.js#L24-L36

**Comment by missinglink** [comment]
One commonality there is that all those calls seem to be using `proj` to reproject the data.

IIRC there is a file required by `proj6` that wasn't required before, it's ends with `.db` and is listed in one of my docker files somewhere, worth checking.

**Comment by Joxit** [comment]
Something like `/usr/share/proj/proj.db` in `pelias/spatial` ?

**Comment by missinglink** [comment]
Yeah, that file is required when using `proj6`, is it present on your system?

**Comment by Joxit** [comment]
Nope, this file is not present, I will try to build from source proj 6.3.2 and see if the file appears

**Comment by Joxit** [comment]
I do have proj files now in `/usr/local/share/proj/` and I'm playing with `PROJ_LIB` and `LD_LIBRARY_PATH`

**Comment by missinglink** [comment]
I've opened this issue https://github.com/JoshuaWise/better-sqlite3/issues/363 over at `better-sqlite3` to discuss allowing the `.loadExtension()` function to accept an `entry_point` param.

**Comment by missinglink** [comment]
https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!topic/spatialite-users/71jnc6QVN-A

https://en.m.wikibooks.org/wiki/Linux_Applications_Debugging_Techniques/The_dynamic_linker

**Comment by missinglink** [comment]
I was playing with again recently and found that I could get `mod_spatialite` to load fine under Ubuntu using python and also the `sqlite3` nom module.

So I suspect there is some linking issue specific to `better-sqlite3`

**Comment by Joxit** [comment]
Thank you for all the time spent for this issue (and your links) ! :heart: 

I used `LD_DEBUG=bindings` in missinglink/gis:buster to find out which dynamic library were used. I found that `libproj.so.13` (5.x) was used instead of `libproj.so.15` (6.x) as you said here https://github.com/pelias/spatial/pull/40#issuecomment-597662927.
So I did some changes here : https://github.com/Joxit/docker-gis/tree/debian

And.... It works inside the docker now :scream: :tada: 

(I uploaded the image for you)
docker run -ti --rm joxit/gis
```
sudo apt update
sudo apt install -y curl git python2
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm install 10
git clone https://github.com/pelias/spatial .
sed -i 's,/bin/sh,/bin/bash,' ./bin/download_sqlite.sh
npm install
npx tap --no-cov --reporter=specy test/environment.js
```

So I need to do a second try with proj6 on my laptop >.<... This will probably work one day...

:memo: : `-o pipefile` do not work when the interpreter is `/bin/sh` on debian... The interpreter must be `/bin/bash`. I don't know why it's working on alpine or maybe it's not interpreted :man_shrugging:

**Comment by missinglink** [comment]
Is it possible to simply set `LD_LIBRARY_PATH` to set the order if imports?

**Comment by Joxit** [comment]
Yes ! On my laptop, with `LD_LIBRARY_PATH` pointing my local library path `/usr/local/lib` the spatialite module seems to load ! :smile: But I still have one `SIGSEGV` somewhere :man_shrugging:

Hum... Sadly only `test/environement.js` were passing in my docker not all tests >.<
Some examples:
```
 FAIL  module/geometry/GeoIndexGeom.test.js 1 OK 1s
  command: /home/docker/.nvm/versions/node/v10.20.1/bin/node
  args:
    - -r
    - /service/gis/node_modules/esm/esm.js
    - module/geometry/GeoIndexGeom.test.js
  exitCode: null
  signal: SIGSEGV

 FAIL  TAP
 ✖ module/geometry/GeoIndexGeom.test.js

  test: TAP
  env: {}
  file: module/geometry/GeoIndexGeom.test.js
  timeout: 30000
  command: /home/docker/.nvm/versions/node/v10.20.1/bin/node
  args:
    - -r
    - /service/gis/node_modules/esm/esm.js
    - module/geometry/GeoIndexGeom.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /service/gis
  exitCode: null
  signal: SIGSEGV
```

I think this is cause by some shared library :thinking:

**Comment by missinglink** [comment]
superseded by https://github.com/pelias/spatial/pull/58

**Pull request closed without merging**
