### PR TITLE
move from circleci to github actions

### PR DESCRIPTION
**Pull request by Joxit**
Remove Circle CI and use only github actions

### CODE REVIEW

**Review by missinglink — APPROVED** [review]
Looks good, just wondering why `ENV HOME` in the docker file and the `bindings` module are required?

**Comment by Joxit** [comment]
The `bindings` fixes a runtime issue, here was the output:

```
test/environment.js 2>
test/environment.js 2> /code/node_modules/better-sqlite3/lib/database.js:9
test/environment.js 2> } = require('bindings')('better_sqlite3.node');
test/environment.js 2>     ^
test/environment.js 2> /code/node_modules/better-sqlite3/lib/database.js:1
test/environment.js 2> Error: Cannot find module 'bindings'
test/environment.js 2> Require stack:
test/environment.js 2> - /code/node_modules/better-sqlite3/lib/database.js
test/environment.js 2> - /code/node_modules/better-sqlite3/lib/index.js
test/environment.js 2> - /code/test/common.js
test/environment.js 2> - /code/test/environment.js
test/environment.js 2>     at Object.<anonymous> (/code/node_modules/better-sqlite3/lib/database.js:9:5)
test/environment.js 2>     at Object.Module._compile (/code/node_modules/source-map-support/source-map-support.js:568:25)
test/environment.js


 FAIL  test/environment.js 476.186ms
  command: /usr/local/bin/node
  args:
    - -r
    - /code/node_modules/esm/esm.js
    - test/environment.js
  exitCode: 1
  signal: null

Suites:   1 failed, 1 of 1 completed
Asserts:  1 failed, of 1
The command '/bin/sh -c npm run env_check && npm t' returned a non-zero code: 1
```

The `ENV HOME` doesn't seem to be needed anymore. I had an error at install where node wanted to write something in `/root/.node-gyp` and this produces an `Error: EACCES: permission denied`. I can't reproduce the error so I removed the `ENV HOME` line, thx :smile:

**Comment by missinglink** [comment]
Hmm I wonder what's going on 🤔

We certainly shouldn't have to require the `bindings` module as a dependency for `better-sqlite3` because it declares it in its own `package.json` 🤷‍♂️ 

https://github.com/WiseLibs/better-sqlite3/blob/master/package.json#L19

I'm not against merging this but it feels like something is not right here...

**Comment by missinglink** [comment]
My suspicion is this flag `--ignore-scripts`, which, as the same says, prevents and lifecycle scripts defined in the `package.json` (preinstall, postinstall) from running.

**Comment by missinglink** [comment]
hmm yeah, so I looked into it a bit more and it seems to be due to a change in behaviour with `npm` since the previous version.

In particular I believe it's due to npm dependencies previously being nested so when we copied `node_modules/better-sqlite3` we got all its dependencies too, which no longer seems to be the case 🤷‍♂️ 

I tried copying the bindings from build step 3 to build step 4 but then I get a similar message that the `file-uri-to-path` dependency of the `bindings` module can't be found, so it's nasty and cascading.

In light of this I think just adding the `bindings` dependency is the cleanest solution :+1:

**Comment by missinglink** [comment]
Thanks! I've also gone into the Circle-CI admin and hit disable there, so hopefully we don't see it running under future PRs

Screenshot 2022-05-28 at 21 38 37

**Comment by Joxit** [comment]
> hmm yeah, so I looked into it a bit more and it seems to be due to a change in behaviour with npm since the previous version.
>
> In particular I believe it's due to npm dependencies previously being nested so when we copied node_modules/better-sqlite3 we got all its dependencies too, which no longer seems to be the case :man_shrugging:

Ok, I understand better why it stopped working overnight...

**Comment by missinglink** [comment]
I'm not certain, but it probably came in with this change https://github.com/pelias/docker-baseimage/commit/a9a926173d248476ec99c9c54a58095c6d0017c0

**Pull request merged**
